batch_size: 256
buffer_size: 10000000
checkpoints_path: BC
device: cuda
discount: 0.99
env: G1JoystickFlatTerrain
dataset_id: playground/G1JoystickFlatTerrain-random-v0
eval_freq: 5000
frac: 1.0
group: bc-g1-random-v0
load_model: ''
max_timesteps: 1000000
max_traj_len: 1000
n_episodes: 10
name: BC
normalize: false
project: CORL
seed: 0
