beta: 0.5
batch_size: 256
buffer_size: 10000000
checkpoints_path: COMBO
device: cuda
discount: 0.99
env: JoystickFlatTerrain
dataset_id: playground/JoystickFlatTerrain-medium-v0
ensemble_size: 5
eval_freq: 5000
expl_noise: 0.1
f: 0.5
gen_freq: 500 #<< alterado de 1000 para 500
group: combo-go1-medium-v0
load_model: ''
max_timesteps: 1000000
model_buffer_size: 100000
model_horizon: 5
model_lr: 3e-4
model_num_trajectories: 500 #<< alterado de 1000 para 2500
n_episodes: 10
name: COMBO
noise_clip: 0.5
normalize: false
normalize_reward: false
policy_freq: 2
policy_noise: 0.2
project: CORL
seed: 0
tau: 0.005
dynamics_epochs: 1 #<< alterado (40, 100, 200, 500)
