batch_size: 256
buffer_size: 10000000
checkpoints_path: BC
device: cuda
discount: 0.99
env: H1JoystickGaitTracking
dataset_id: playground/H1JoystickGaitTracking-foward-expert-v1
eval_freq: 5000
frac: 1.0
group: bc-h1-expert-v1
load_model: ''
max_timesteps: 1000000
max_traj_len: 1000
n_episodes: 10
name: BC
normalize: false
project: Offline-Benchmark
seed: 0
