awac_lambda: 0.1
batch_size: 256
buffer_size: 10000000
checkpoints_path: AWAC/AWAC-G1JoystickFlatTerrain-618d2b34
dataset_id: /home/fabrycio/rl_akcit/playground/G1JoystickFlatTerrain-expert-v0
deterministic_torch: false
device: cuda
env: G1JoystickFlatTerrain
eval_frequency: 100
gamma: 0.99
group: awac-go1-expert-v0
hidden_dim: 256
learning_rate: 0.0003
n_test_episodes: 10
name: AWAC-G1JoystickFlatTerrain-618d2b34
normalize_reward: false
num_train_ops: 500
project: CORL
seed: 0
tau: 0.005
test_seed: 69
