alpha: 2.5
batch_size: 256
buffer_size: 10000000
checkpoints_path: TD3-BC
device: cuda
discount: 0.99
env: Go2Handstand
dataset_id: playground/Go2Handstand-expert-v1
eval_freq: 5000
expl_noise: 0.1
group: td3-bc-go2-expert-v1
load_model: ''
max_timesteps: 1000000
n_episodes: 10
name: TD3-BC
noise_clip: 0.5
normalize: false
normalize_reward: false
policy_freq: 2
policy_noise: 0.2
project: CORL
seed: 0
tau: 0.005
