python train_jax_ppo.py --env_name Go2JoystickFlatTerrain  --use_wandb \
    --episode_length 2000 \
    --learning_rate 1e-4 \
    --entropy_cost 0.02 \
    --max_grad_norm 2.0 \
    --num_evals 20 \
    --num_minibatches 64 \
    --num_updates_per_batch 8 \
    --unroll_length 40 \
    --reward_scaling 2.0 \
    --num_envs 16384