project: CORL
awac_lambda: 0.1
hidden_dim: 256
learning_rate: 0.0003
gamma: 0.99
tau: 0.005
batch_size: 256
buffer_size: 10000000
eval_frequency: 1000
n_test_episodes: 10
num_train_ops: 1000000
seed: 42
test_seed: 69
device: cuda
deterministic_torch: false
checkpoints_path: AWAC
env: Footstand
dataset_id: playground/Footstand-medium-v0
group: awac-go1-medium-v0
