awac_lambda: 0.1
batch_size: 256
buffer_size: 10000000
checkpoints_path: AWAC
deterministic_torch: false
device: cuda
env: Go1JoystickFlatTerrain
dataset_id: playground/Go1JoystickFlatTerrain-expert-v0
eval_frequency: 1000
gamma: 0.99
group: awac-go1-expert-v0
hidden_dim: 256
learning_rate: 0.0003
n_test_episodes: 10
num_train_ops: 1000000
project: CORL
seed: 42
tau: 0.005
test_seed: 69
