project: CORL
discount: 0.99
tau: 0.005
beta: 3.0
iql_tau: 0.8
iql_deterministic: false
max_timesteps: 1000000
buffer_size: 10000000
batch_size: 256
normalize: true
normalize_reward: false
vf_lr: 0.0003
qf_lr: 0.0003
actor_lr: 0.0003
actor_dropout: 0.1
eval_freq: 5000
n_episodes: 10
seed: 0
device: cuda
load_model: ''
checkpoints_path: null
env: JoystickRoughTerrain
dataset_id: JoystickRoughTerrain-medium
group: iql-JoystickRoughTerrain-medium-multiseed-v0
