batch_size: 256
buffer_size: 10000000
checkpoints_path: checkpoints/BC
device: cuda
discount: 0.99
env: Go2Handstand
dataset_id: playground/Go2Handstand-medium-v1
eval_freq: 5000
frac: 1.0
group: bc-go2-medium-v1
load_model: ''
max_timesteps: 1000000
max_traj_len: 1000
n_episodes: 10
name: BC
normalize: false
project: Offline-Benchmark
seed: 0
